Algoritmo "areaQuadrado"
//Este algoritmo solicita o lado e calcula a  area do quadrado

Var
lado,area: real

Inicio
//entrada
escreval("-------------------------")
escreval("Digite o Lado do Quadrado")
escreval("-------------------------")
leia(lado)
escreval("-------------------------")

//processamento
area <- lado^2

//saida
escreval("A área do Quadrado é:", area)

Fimalgoritmo